👷‍♂️ ci: upload to releases

diff --git a/.github/workflows/postgresql-to-sqlite.yml b/.github/workflows/postgresql-to-sqlite.yml
--- a/.github/workflows/postgresql-to-sqlite.yml
+++ b/.github/workflows/postgresql-to-sqlite.yml
@@ -34,10 +34,65 @@ jobs:
           sed 's/public\.//' -i  dosleg.sql
           chmod +x pg2sqlite-1.0.1.jar
           java -jar pg2sqlite-1.0.1.jar -d dosleg.sql -o sqlite.db
-
-      - name: Upload a Build Artifact
-        uses: actions/upload-artifact@v3.1.2
+          
+      - name: Calculer la checksum de la base SQLite
+        uses: jmgilman/actions-generate-checksum@v1
         with:
-          name: dosleg
-          path: sqlite.db
-
+          patterns: |
+            sqlite.db
+          output: checksum.txt
+          
+      - name: Récuperer la checksum de la précédente release
+        id: get_previous_checksum
+        run: |
+          release=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest")
+          if [[ $(echo "${release}" | jq -r '.message') == "Not Found" ]]; then
+            echo "Aucune release précédente n'existe."
+            echo "" > previous_checksum.txt
+          else
+            echo "${release}" | jq -r '.body' > previous_checksum.txt
+          fi
+      
+      - name: Vérifier la nécéssité d'une release
+        id: compare_checksums
+        continue-on-error: true
+        run: |
+          checksum=$(cat checksum.txt) 
+          previous_checksum=$(cat previous_checksum.txt)
+          if [[ "${previous_checksum}" == "" ]]; then
+            echo "Aucune release précédente n'existe. Téléchargement et téléversement de la nouvelle release."
+            echo "checksum=${checksum}" >> $GITHUB_OUTPUT
+            exit 0
+          elif [[ "${previous_checksum}" != "${checksum}" ]]; then
+            echo "Les checksums sont différents. Téléchargement et téléversement de la nouvelle release."
+            echo "checksum=${checksum}" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Les checksums sont identiques. Aucune action nécessaire."
+            exit 1
+          fi
+      
+      - name: Créer une release
+        uses: actions/create-release@v1
+        id: create_release
+        if: steps.compare_checksums.outcome == 'success'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ steps.compare_checksum.outputs.checksum }}
+          release_name: Release ${{ steps.compare_checksum.outputs.checksum }}
+          body: ${{ steps.compare_checksum.outputs.checksum }}
+          draft: false
+          prerelease: false
+          
+      - name: Téléverser la base sur la release
+        id: upload-release-asset 
+        uses: actions/upload-release-asset@v1
+        if: steps.compare_checksums.outcome == 'success'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ./sqlite.db
+          asset_name: sqlite.db
+          asset_content_type: application/x-sqlite3
